"""empty message

Revision ID: 0f8f577bca34
Revises: d54218eb8f84
Create Date: 2024-02-09 00:42:16.982942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8f577bca34'
down_revision = 'd54218eb8f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_responses', schema=None) as batch_op:
        batch_op.drop_index('deleted_question_ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_responses', schema=None) as batch_op:
        batch_op.create_index('deleted_question_ID', ['deleted_questionID'], unique=False)

    # ### end Alembic commands ###
