"""empty message

Revision ID: d54218eb8f84
Revises: 
Create Date: 2024-02-09 00:36:03.440870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd54218eb8f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answerID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_constraint('answer_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('answer_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'term', ['termID'], ['termID'])
        batch_op.create_foreign_key(None, 'question', ['questionID'], ['questionID'])

    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.alter_column('audioLocation',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('deleted_module', schema=None) as batch_op:
        batch_op.drop_constraint('deleted_userID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userID'], ['userID'])

    with op.batch_alter_table('deleted_question', schema=None) as batch_op:
        batch_op.drop_constraint('deleted_question_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('deleted_question_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'audio', ['audioID'], ['audioID'])
        batch_op.create_foreign_key(None, 'image', ['imageID'], ['imageID'])

    with op.batch_alter_table('deleted_term', schema=None) as batch_op:
        batch_op.drop_constraint('deleted_term_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('deleted_term_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'audio', ['audioID'], ['audioID'])
        batch_op.create_foreign_key(None, 'image', ['imageID'], ['imageID'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['groupCode'])

    with op.batch_alter_table('group_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupModuleID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_constraint('moduleID', type_='foreignkey')
        batch_op.drop_constraint('groupID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['groupID'], ['groupID'])
        batch_op.create_foreign_key(None, 'module', ['moduleID'], ['moduleID'])

    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupUserID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('accessLevel',
               existing_type=mysql.ENUM('st', 'ta', 'pf'),
               type_=sa.Enum('st', 'pf', 'ta', name='accesslevel'),
               existing_nullable=False,
               existing_server_default=sa.text("'st'"))
        batch_op.drop_constraint('group_user_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('group_user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['groupID'], ['groupID'])
        batch_op.create_foreign_key(None, 'user', ['userID'], ['userID'])

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('imageLocation',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('logged_answer', schema=None) as batch_op:
        batch_op.drop_constraint('logged_answer_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('logged_answer_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['questionID'], ['questionID'])
        batch_op.create_foreign_key(None, 'term', ['termID'], ['termID'])

    with op.batch_alter_table('mentor_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('mentor_preferences_userID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userID'], ['userID'])

    with op.batch_alter_table('mentor_question_frequency', schema=None) as batch_op:
        batch_op.drop_constraint('module_key', type_='foreignkey')
        batch_op.create_foreign_key(None, 'module', ['moduleID'], ['moduleID'])

    with op.batch_alter_table('mentor_responses', schema=None) as batch_op:
        batch_op.drop_constraint('mentor_responses_sessionID', type_='foreignkey')
        batch_op.drop_constraint('mentor_responses_questionID', type_='foreignkey')
        batch_op.drop_constraint('deleted_question_ID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['sessionID'], ['sessionID'])
        batch_op.create_foreign_key(None, 'question', ['questionID'], ['questionID'])

    with op.batch_alter_table('module_question', schema=None) as batch_op:
        batch_op.drop_constraint('module_question_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('module_question_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['questionID'], ['questionID'])

    with op.batch_alter_table('multiple_choice_answers', schema=None) as batch_op:
        batch_op.drop_constraint('multiple_choice_answers_questionID', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['questionID'], ['questionID'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('question_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('question_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'audio', ['audioID'], ['audioID'])
        batch_op.create_foreign_key(None, 'image', ['imageID'], ['imageID'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint('session_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('session_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('deleted_module_key', type_='foreignkey')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tag_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'term', ['termID'], ['termID'])

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_constraint('term_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('term_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image', ['imageID'], ['imageID'])
        batch_op.create_foreign_key(None, 'audio', ['audioID'], ['audioID'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokenID', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('userID_preferences', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userID'], ['userID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('userID_preferences', 'user', ['userID'], ['userID'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('tokenID')

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('term_ibfk_2', 'audio', ['audioID'], ['audioID'], onupdate='SET NULL', ondelete='SET NULL')
        batch_op.create_foreign_key('term_ibfk_1', 'image', ['imageID'], ['imageID'], onupdate='SET NULL', ondelete='SET NULL')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tag_ibfk_1', 'term', ['termID'], ['termID'], ondelete='CASCADE')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_foreign_key('deleted_module_key', 'deleted_module', ['deleted_moduleID'], ['moduleID'])
        batch_op.create_foreign_key('session_ibfk_2', 'module', ['moduleID'], ['moduleID'], ondelete='SET NULL')
        batch_op.create_foreign_key('session_ibfk_1', 'user', ['userID'], ['userID'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_ibfk_1', 'audio', ['audioID'], ['audioID'], ondelete='SET NULL')
        batch_op.create_foreign_key('question_ibfk_2', 'image', ['imageID'], ['imageID'], ondelete='SET NULL')

    with op.batch_alter_table('multiple_choice_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('multiple_choice_answers_questionID', 'question', ['questionID'], ['questionID'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('module_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('module_question_ibfk_1', 'module', ['moduleID'], ['moduleID'], ondelete='CASCADE')
        batch_op.create_foreign_key('module_question_ibfk_2', 'question', ['questionID'], ['questionID'], ondelete='CASCADE')

    with op.batch_alter_table('mentor_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deleted_question_ID', 'deleted_question', ['deleted_questionID'], ['questionID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('mentor_responses_questionID', 'question', ['questionID'], ['questionID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('mentor_responses_sessionID', 'session', ['sessionID'], ['sessionID'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('mentor_question_frequency', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('module_key', 'module', ['moduleID'], ['moduleID'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('mentor_preferences', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mentor_preferences_userID', 'user', ['userID'], ['userID'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('logged_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('logged_answer_ibfk_1', 'question', ['questionID'], ['questionID'], ondelete='SET NULL')
        batch_op.create_foreign_key('logged_answer_ibfk_4', 'term', ['termID'], ['termID'], ondelete='SET NULL')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('imageLocation',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)

    with op.batch_alter_table('group_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_user_ibfk_1', 'user', ['userID'], ['userID'], ondelete='CASCADE')
        batch_op.create_foreign_key('group_user_ibfk_2', 'group', ['groupID'], ['groupID'], ondelete='CASCADE')
        batch_op.alter_column('accessLevel',
               existing_type=sa.Enum('st', 'pf', 'ta', name='accesslevel'),
               type_=mysql.ENUM('st', 'ta', 'pf'),
               existing_nullable=False,
               existing_server_default=sa.text("'st'"))
        batch_op.drop_column('groupUserID')

    with op.batch_alter_table('group_module', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('groupID', 'group', ['groupID'], ['groupID'], ondelete='CASCADE')
        batch_op.create_foreign_key('moduleID', 'module', ['moduleID'], ['moduleID'], ondelete='CASCADE')
        batch_op.drop_column('groupModuleID')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('deleted_term', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deleted_term_ibfk_1', 'image', ['imageID'], ['imageID'], onupdate='SET NULL', ondelete='SET NULL')
        batch_op.create_foreign_key('deleted_term_ibfk_2', 'audio', ['audioID'], ['audioID'], onupdate='SET NULL', ondelete='SET NULL')

    with op.batch_alter_table('deleted_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deleted_question_ibfk_1', 'audio', ['audioID'], ['audioID'], ondelete='SET NULL')
        batch_op.create_foreign_key('deleted_question_ibfk_2', 'image', ['imageID'], ['imageID'], ondelete='SET NULL')

    with op.batch_alter_table('deleted_module', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deleted_userID', 'user', ['userID'], ['userID'], ondelete='SET NULL')

    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.alter_column('audioLocation',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answer_ibfk_1', 'question', ['questionID'], ['questionID'], ondelete='CASCADE')
        batch_op.create_foreign_key('answer_ibfk_2', 'term', ['termID'], ['termID'], ondelete='CASCADE')
        batch_op.drop_column('answerID')

    # ### end Alembic commands ###
