# This YAML file is used to stop the PM2 processes on the dev server, pull the latest changes from the GitHub repository, and restart the PM2 processes. The SSH keys are stored in the GitHub repository secrets and are used to authenticate the GitHub Actions workflow with the dev server.
name: Update Dev Server
concurrency: ${{ github.workflow }}

on:
    push:
        branches:
            - dev
    workflow_dispatch:

jobs:
    deploy:
        name: Pull from GitHub
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Keys
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts
            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.DEV_SSH_HOST }}
                  username: ${{ secrets.DEV_SSH_USER }}
                  key: ${{ secrets.DEV_SSH_KEY }}
                  script_stop: true
                  script: |
                      cd /var/www/ELLE-Website-API
                      git pull
                      pm2 restart elle_api
                      cd templates/
                      npm install
                      npm run build
                      pm2 restart elle_website
