---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies and Build
        run: |
          # Install dependencies for Next.js frontend
          cd templates
          npm install

          # Build Next.js frontend
          npm run build
          if [ $? -ne 0 ]; then
            echo "Next.js app failed to build!"
            exit 1
          else
            echo "Next.js app built successfully!"
          fi

          # Install Flask dependencies
          cd ..
          pip3 install -r requirements.txt

          python3 -c 'import __init__' || {
          echo "Flask app failed to import"
          exit 1
          }
          echo "Flask app dependencies installed and app imported successfully"

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: "root"
          key: ${{ secrets.KEY }}
          script: |
            cd ELLE-Website-API/
            git pull origin ${{ github.ref_name }}

            # Install dependencies and build frontend
            cd templates
            npm install
            npm run build
            if [ $? -ne 0 ]; then
              echo "Next.js app failed to build!"
              exit 1
            else
              echo "Next.js app built successfully!"
            fi

            # Restart applications
            pm2 restart all
            sudo systemctl restart apache2

